<a href="https://colab.research.google.com/github/ElaineKelmaMoura/Analise_Obesidade-PIB-per-capita/blob/main/Conhe%C3%A7a_o_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Projeto de obesidade entre adultos nos anos de 1965 e 2016.

* Limpe os dados do DataFrame, criando uma coluna de nome  'Obesity' que conterá os valores de obesidade. Transforme em float as colunas que porventura foram importadas como strings.

In [207]:
import pandas as pd
import numpy as np

In [208]:
df_obesity = pd.read_csv("obesity_cleaned.csv") #Leitura do arquivo

In [209]:
df_obesity

       Unnamed: 0      Country  Year       Obesity (%)         Sex
0               0  Afghanistan  1975     0.5 [0.2-1.1]  Both sexes
1               1  Afghanistan  1975     0.2 [0.0-0.6]        Male
2               2  Afghanistan  1975     0.8 [0.2-2.0]      Female
3               3  Afghanistan  1976     0.5 [0.2-1.1]  Both sexes
4               4  Afghanistan  1976     0.2 [0.0-0.7]        Male
...           ...          ...   ...               ...         ...
24565       24565     Zimbabwe  2015     4.5 [2.4-7.6]        Male
24566       24566     Zimbabwe  2015  24.8 [18.9-31.3]      Female
24567       24567     Zimbabwe  2016  15.5 [12.0-19.2]  Both sexes
24568       24568     Zimbabwe  2016     4.7 [2.5-8.0]        Male
24569       24569     Zimbabwe  2016  25.3 [19.1-32.0]      Female

[24570 rows x 5 columns]

In [210]:
#Verificando as colunas
df_obesity["Year"].head(5)

0    1975
1    1975
2    1975
3    1976
4    1976
Name: Year, dtype: int64

In [211]:
df_obesity["Obesity (%)"].head(5)

0    0.5 [0.2-1.1]
1    0.2 [0.0-0.6]
2    0.8 [0.2-2.0]
3    0.5 [0.2-1.1]
4    0.2 [0.0-0.7]
Name: Obesity (%), dtype: object

In [212]:
df_obesity["Obesity (%)"].iloc[0]

'0.5 [0.2-1.1]'

In [213]:
df_obesity["Obesity (%)"].value_counts()

Obesity (%)
No data            504
0.4 [0.1-1.0]       55
0.6 [0.2-1.3]       47
0.3 [0.1-0.7]       46
0.3 [0.1-0.8]       46
                  ...
12.5 [7.7-18.7]      1
3.8 [1.8-6.9]        1
9.0 [6.2-12.6]       1
13.3 [8.4-19.5]      1
6.9 [4.2-10.7]       1
Name: count, Length: 16375, dtype: int64

In [214]:
df_obesity.columns

Index(['Unnamed: 0', 'Country', 'Year', 'Obesity (%)', 'Sex'], dtype='object')

In [215]:
#Deletando coluna
del df_obesity['Unnamed: 0']

In [216]:
#Criando uma nova coluna, e uma função para jogar fora informações desnecessárias.

In [217]:
df_obesity["Obesity (%)"]

0           0.5 [0.2-1.1]
1           0.2 [0.0-0.6]
2           0.8 [0.2-2.0]
3           0.5 [0.2-1.1]
4           0.2 [0.0-0.7]
               ...
24565       4.5 [2.4-7.6]
24566    24.8 [18.9-31.3]
24567    15.5 [12.0-19.2]
24568       4.7 [2.5-8.0]
24569    25.3 [19.1-32.0]
Name: Obesity (%), Length: 24570, dtype: object

In [218]:
df_obesity["Obesity"] = df_obesity["Obesity (%)"].apply(lambda x: x.split()[0])

In [219]:
df_obesity['Obesity'].head(5)#verificando o tipo da coluna

0    0.5
1    0.2
2    0.8
3    0.5
4    0.2
Name: Obesity, dtype: object

In [220]:
df_obesity['Obesity'].value_counts()#Necessário tirar o No

Obesity
No      504
0.4     222
0.6     218
0.5     217
0.7     210
       ...
56.8      1
62.4      1
60.0      1
62.6      1
60.3      1
Name: count, Length: 602, dtype: int64

In [221]:
df_obesity.loc[df_obesity["Obesity"] == "No", "Obesity"] = np.nan

In [222]:
df_obesity["Obesity"] = df_obesity["Obesity"].dropna()

In [223]:
df_obesity["Obesity"].value_counts()

Obesity
0.4     222
0.6     218
0.5     217
0.7     210
0.8     201
       ...
61.9      1
56.8      1
62.1      1
42.7      1
46.5      1
Name: count, Length: 601, dtype: int64

In [224]:
#Transformando para float
df_obesity["Obesity"] = df_obesity["Obesity"].apply(lambda x: float(x))

In [225]:
#Transformando para int
df_obesity["Year"] = df_obesity["Year"].apply(lambda x: int(x))

In [226]:
df_obesity

           Country  Year       Obesity (%)         Sex  Obesity
0      Afghanistan  1975     0.5 [0.2-1.1]  Both sexes      0.5
1      Afghanistan  1975     0.2 [0.0-0.6]        Male      0.2
2      Afghanistan  1975     0.8 [0.2-2.0]      Female      0.8
3      Afghanistan  1976     0.5 [0.2-1.1]  Both sexes      0.5
4      Afghanistan  1976     0.2 [0.0-0.7]        Male      0.2
...            ...   ...               ...         ...      ...
24565     Zimbabwe  2015     4.5 [2.4-7.6]        Male      4.5
24566     Zimbabwe  2015  24.8 [18.9-31.3]      Female     24.8
24567     Zimbabwe  2016  15.5 [12.0-19.2]  Both sexes     15.5
24568     Zimbabwe  2016     4.7 [2.5-8.0]        Male      4.7
24569     Zimbabwe  2016  25.3 [19.1-32.0]      Female     25.3

[24570 rows x 5 columns]

In [227]:
df_obesity.set_index("Year", inplace=True)#Defenindo o index - Ano

In [228]:
df_obesity

          Country       Obesity (%)         Sex  Obesity
Year
1975  Afghanistan     0.5 [0.2-1.1]  Both sexes      0.5
1975  Afghanistan     0.2 [0.0-0.6]        Male      0.2
1975  Afghanistan     0.8 [0.2-2.0]      Female      0.8
1976  Afghanistan     0.5 [0.2-1.1]  Both sexes      0.5
1976  Afghanistan     0.2 [0.0-0.7]        Male      0.2
...           ...               ...         ...      ...
2015     Zimbabwe     4.5 [2.4-7.6]        Male      4.5
2015     Zimbabwe  24.8 [18.9-31.3]      Female     24.8
2016     Zimbabwe  15.5 [12.0-19.2]  Both sexes     15.5
2016     Zimbabwe     4.7 [2.5-8.0]        Male      4.7
2016     Zimbabwe  25.3 [19.1-32.0]      Female     25.3

[24570 rows x 4 columns]



*  Qual o percentual médio de obesidade por sexo no mundo no ano de 2015?

In [246]:
df_obesity[df_obesity.index == 2015].groupby("Sex").mean(numeric_only=True)

              Obesity
Sex
Both sexes  19.508377
Female      22.899476
Male        15.980628



*   Quais são os 5 países com a maior e menor taxa de aumento nos índices de obesidade no período observado?

In [ ]:
df_obesity_start = df_obesity[df_obesity.index == 1975]
df_obesity_end = df_obesity[df_obesity.index == 2016]

In [ ]:
df_obesity_start.head(5)

In [ ]:
#Colocando como índice de ambos o país
df_obesity_start.set_index("Country", inplace=True)
df_obesity_end.set_index("Country", inplace=True)

In [ ]:
#Obsidade de todos os países no ano final por país
df_obesity_end[df_obesity_end["Sex"] == "Both sexes"]["Obesity"]

In [ ]:
#fazendo analise com ambos os sexos
df_obesity_evol = df_obesity_end[df_obesity_end["Sex"] == "Both sexes"]["Obesity"] - df_obesity_start[df_obesity_start["Sex"] == "Both sexes"]["Obesity"]

In [ ]:
df_obesity_evol #Evoluções percentuais no período observado de todos os países.

In [ ]:
df_obesity_evol.sort_values() #Ordenando

In [ ]:
df_obesity_evol.sort_values().dropna().head(5) #Jogando fora países com informações NaN / 5 países com menor evolução

In [ ]:
df_obesity_evol.sort_values().dropna().tail(5) #Países com maior evolução

In [ ]:
df_obesity_end[df_obesity_end.index == "Tuvalu"]



*   Quais os países com maiores e menores níveis percentuais de obesidade em 2015?

In [ ]:
df_2015 = df_obesity[df_obesity.index == 2015]
df_2015 [df_2015["Obesity"] == df_2015["Obesity"].max()]



*   Qual a diferença média percentual de obesidade entre sexos ao longo dos anos para o Brasil?

In [ ]:
df_brazil = df_obesity[df_obesity["Country"] == "Brazil"]

In [ ]:
df_brazil

In [ ]:
df_brazil[df_brazil["Sex"] == "Female"]["Obesity"] - df_brazil[df_brazil["Sex"] == "Male"]["Obesity"]

In [ ]:
(df_brazil[df_brazil["Sex"] == "Female"]["Obesity"] - df_brazil[df_brazil["Sex"] == "Male"]["Obesity"]).plot()



*   Você conseguiria plotar um gráfico mostrando a evolução da obsidade para ambos sexos no mundo?

In [ ]:
# fazer uma análise global
df_both = df_obesity[df_obesity["Sex"] == "Both sexes"]
df_both

In [ ]:
df_both.groupby("Year")["Obesity"].mean().plot()